

export const REQUEST_COLLECTIONS = 'REQUEST_COLLECTIONS';
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const REQUEST_COLLECTION_DETAILS = 'REQUEST_COLLECTION_DETAILS';
export const FETCH_COLLECTION_DETAILS = 'FETCH_COLLECTION_DETAILS';
export const REQUEST_COLLECTIONS_BY_LOCATION = 'REQUEST_COLLECTIONS_BY_LOCATION';
